<a href="https://colab.research.google.com/github/np03cs4a240319-eng/Concept-and-technology-of-AI/blob/main/divyanikhatri_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Initialize an empty array with size 2x2
arr_empty = np.empty((2, 2))
print("1. Empty 2x2 array:\n", arr_empty)


# 2. Initialize an all-one array with size 4x2
arr_ones = np.ones((4, 2))
print("\n2. All ones 4x2 array:\n", arr_ones)


# 3. Return a new array of given shape and type, filled with a fill value
arr_full = np.full((3, 3), 7)  # Example: fill with 7
print("\n3. Full 3x3 array filled with 7:\n", arr_full)


# 4. Return a new array of zeros with same shape and type as a given array
a = np.array([[1, 2], [3, 4]])
arr_zeros_like = np.zeros_like(a)
print("\n4. Zeros like given array a:\n", arr_zeros_like)


# 5. Return a new array of ones with same shape and type as a given array
b = np.array([[5, 6], [7, 8]])
arr_ones_like = np.ones_like(b)
print("\n5. Ones like given array b:\n", arr_ones_like)


# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("\n6. Array from list:\n", arr_from_list)


1. Empty 2x2 array:
 [[5.10710757e-316 0.00000000e+000]
 [6.55309168e-310 6.55309168e-310]]

2. All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full 3x3 array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like given array a:
 [[0 0]
 [0 0]]

5. Ones like given array b:
 [[1 1]
 [1 1]]

6. Array from list:
 [1 2 3 4]


In [2]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr_range = np.arange(10, 50)
print("1. Array 10 to 49:\n", arr_range)

# 2. Create a 3x3 matrix with values from 0 to 8
arr_matrix = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix 0 to 8:\n", arr_matrix)

# 3. Create a 3x3 identity matrix
identity = np.eye(3)
print("\n3. Identity Matrix:\n", identity)

# 4. Create a random array of size 30 and find the mean
rand_arr = np.random.random(30)
print("\n4. Mean of random 30 values:", rand_arr.mean())

# 5. Create a 10x10 random array and find min & max
rand_10x10 = np.random.random((10, 10))
print("\n5. Min:", rand_10x10.min(), " Max:", rand_10x10.max())

# 6. Create a zero array of size 10 and replace 5th element with 1
arr_zero = np.zeros(10)
arr_zero[4] = 1
print("\n6. Zero array with 5th element = 1:\n", arr_zero)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
rev_arr = arr[::-1]
print("\n7. Reversed array:\n", rev_arr)

# 8. Create a 2D array with 1 on border and 0 inside
border = np.ones((5, 5))
border[1:-1, 1:-1] = 0
print("\n8. Border 1, inside 0:\n", border)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard pattern:\n", checkerboard)

1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random 30 values: 0.45639872007626475

5. Min: 0.006965325161072511  Max: 0.9942046973840897

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
 [0 4 0 0 2 1]

8. Border 1, inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
