<a href="https://colab.research.google.com/github/np03cs4a240319-eng/Concept-and-technology-of-AI/blob/main/week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Initialize an empty array with size 2×2
arr_empty = np.empty((2, 2))
print("1. Empty 2x2 array:\n", arr_empty)

# 2. Initialize an all-one array with size 4×2
arr_ones_4x2 = np.ones((4, 2))
print("\n2. All-one 4x2 array:\n", arr_ones_4x2)

# 3. New array of given shape/type filled with fill_value (using np.full)
shape = (3, 3)
fill_value = 7
arr_full = np.full(shape, fill_value)
print("\n3. Full array:\n", arr_full)

# 4. New array of zeros with same shape/type as a given array (np.zeros_like)
given_array = np.array([[1, 2, 3], [4, 5, 6]])
arr_zeros_like = np.zeros_like(given_array)
print("\n4. Zeros like given array:\n", arr_zeros_like)

# 5. New array of ones with same shape/type as a given array (np.ones_like)
arr_ones_like = np.ones_like(given_array)
print("\n5. Ones like given array:\n", arr_ones_like)

# 6. Convert an existing list into a numpy array
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("\n6. List to NumPy array:\n", np_array)



1. Empty 2x2 array:
 [[6.64496663e-316 0.00000000e+000]
 [2.89468780e-229 1.81320626e-287]]

2. All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like given array:
 [[0 0 0]
 [0 0 0]]

5. Ones like given array:
 [[1 1 1]
 [1 1 1]]

6. List to NumPy array:
 [1 2 3 4]
